"""empty message

Revision ID: 6663ba7a0706
Revises: 
Create Date: 2024-02-18 21:02:13.379207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6663ba7a0706'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('first_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=20), nullable=True),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('postcode', sa.String(length=8), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('building_name_number', sa.String(length=50), nullable=True),
    sa.Column('face_image_path', sa.String(length=50), nullable=True),
    sa.Column('user_activate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('blog_activate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('board_activate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('second_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('firstcategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firstcategory_id'], ['first_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('u_cardnumber', sa.String(length=16), nullable=True),
    sa.Column('u_goodthru_year', sa.Integer(), nullable=True),
    sa.Column('u_goodthru_month', sa.Integer(), nullable=True),
    sa.Column('u_cardnominee', sa.String(length=20), nullable=True),
    sa.Column('u_bankcode', sa.String(length=4), nullable=True),
    sa.Column('u_branchcode', sa.String(length=3), nullable=True),
    sa.Column('u_deposititem', sa.String(length=1), nullable=True),
    sa.Column('u_accountnumber', sa.String(length=7), nullable=True),
    sa.Column('u_accountnominee', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('third_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('secondcategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['secondcategory_id'], ['second_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('firstcategory_id', sa.Integer(), nullable=True),
    sa.Column('secondcategory_id', sa.Integer(), nullable=True),
    sa.Column('thirdcategory_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('postage', sa.Integer(), nullable=False),
    sa.Column('movie_path', sa.String(length=255), nullable=True),
    sa.Column('movieflag', sa.Boolean(), nullable=False),
    sa.Column('transactionflag', sa.Boolean(), nullable=False),
    sa.Column('shippingflag', sa.Boolean(), nullable=False),
    sa.Column('receiptflag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['condition_id'], ['item_condition.id'], ),
    sa.ForeignKeyConstraint(['firstcategory_id'], ['first_category.id'], ),
    sa.ForeignKeyConstraint(['secondcategory_id'], ['second_category.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thirdcategory_id'], ['third_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('paymentmethod_id', sa.Integer(), nullable=True),
    sa.Column('shippingaddress', sa.String(length=100), nullable=False),
    sa.Column('totalamount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['paymentmethod_id'], ['payment_method.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_transfer_pay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('bankcode', sa.String(length=4), nullable=False),
    sa.Column('branchcode', sa.String(length=3), nullable=False),
    sa.Column('deposititem', sa.String(length=1), nullable=False),
    sa.Column('accountnumber', sa.String(length=7), nullable=False),
    sa.Column('accountnominee', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_card_pay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('cardnumber', sa.String(length=16), nullable=False),
    sa.Column('goodthru', sa.String(length=4), nullable=False),
    sa.Column('pin', sa.String(length=3), nullable=False),
    sa.Column('cardnominee', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_card_pay')
    op.drop_table('account_transfer_pay')
    op.drop_table('trading_messages')
    op.drop_table('purchase')
    op.drop_table('item_image')
    op.drop_table('item')
    op.drop_table('third_category')
    op.drop_table('comment')
    op.drop_table('user_payments')
    op.drop_table('second_category')
    op.drop_table('follow')
    op.drop_table('chat')
    op.drop_table('board')
    op.drop_table('blogs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('payment_method')
    op.drop_table('item_condition')
    op.drop_table('image')
    op.drop_table('first_category')
    # ### end Alembic commands ###
